error: Add clarifying documentation to ResultExt & WrapErr methods.
In general, the with_context method is preferable to context, since it
delays construction of the String until an error object is actually
needed (that is, until an error actually occurs).

The added documentation clarifies this, as well as the fact that
context is still preferable _if the intended message String has
already been constructed_.

Analogously, wrap_err_with is preferable to wrap_err, and similar
documentation is added.