error: Replace String with Cow<'static, str>.
The error type used throughout Swanky, swanky_error::Error, was
defined to contain a String message and a Vec of String
messages (providing additional context to the error).

Requiring that these strings be allocated is not ideal, as often the
messages / context are just string literals.

By using Cow<'static, str> instead of String, we allow _both_ &'static
str (string literals) _and_ String (or, of course, &'static String) to
be used, saving on allocations whenever a literal would suffice.

This change comes with a corresponding update to every method that
previously accepted a String: They now accept anything that can be
converted Into the Cow type; this is the key to accepting String,
&'static str, and anything else with an infallible conversion.

Note that we also update the macro definitions (bail!, ensure!,
swanky_error!) to support literals properly.

Downstream, the only necessary change at this point to keep a working
build was removing now-unnecessary/incorrect & in uses of
ok_or_swanky_error, which has had its type normalized to the rest of
the crate's API.
Other potential improvements will be handled in future commits.